# Generated by Django 4.2.10 on 2024-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_guest_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='guest',
            name='partition_key',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name='guest',
            table=None,
        ),
    ]
