# Generated by Django 4.2.10 on 2024-04-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_guest_mobile_number_alter_guest_partition_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=50)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('booking_status', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='guest',
            name='id',
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
